server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: Bosssoft@2021
      jdbc-url: jdbc:mysql://10.100.32.144:9009/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
